apiVersion: apps/v1
kind: Deployment
metadata:
  name: flower-app-deployment
spec:  #it defines the desired state of the deployment
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:  #it defines the pod template used by the deployment
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: flower-container
        image: harishkandru/transaction-history:3.0
        resources:
          limits:
            memory: "500Mi"
            cpu: "300m"
          requests: 
            memory: "64Mi"
            cpu: "250m"
        ports:
        - containerPort: 3015

---
apiVersion: v1
kind: Service
metadata:
  name: flower-app-service
spec:
  selector:
    app: web
  ports:
  - port: 3017 #this is the port that the service will expose and you want to access the application
    targetPort: 3015 #this is the port that the container is listening on and application is running
    protocol: TCP
  type: LoadBalancer
